### ISSUE TITLE
Major chords 1st inversion

### ISSUE THREAD

**Issue by flyingCarpet33** [tonaljs/tonal#242] opened 2021-02-09 11:01 UTC
Hi guys, not a programmer myself but i use this software to teach myself the piano. Gotta say, amazing work, absolutely love it!

The only minor issue I've noticed that all 1st inversions of major scales are indicated as minor #5s.

For example an F major chord (F A C) played in 1st inversion (A C F) is indicated as Am#5, where F/A would make more sense.

Keep up the good work!

**Comment by daladim** [comment] 2022-01-20 20:37
I have exactly the same issue.
I'm using [chord-display](https://github.com/rednetio/chord-display) if that matters, and it indeed puzzles me when trying to learn chords with inversions.

Minor chords are working as I expect: (C, Eb, G) displays as a Cm chord, as well as its inversions (Eb, G, C4 that is shown as Cm/Eb) and (G, C4, Eb4 that is shown as Cm/G)

However, for major chords:
* (C, E, G) is correctly shown as C
* (E, G, C4) is shown as Em#5 (I expected C/E)
* (G, C4, E4) is correctly shown as C/G

I'm not good enough at music theory to know whether Em#5 is valid, but I'd like it to be shown as C, or C/E.

I'm not sure either whether that's a duplicate of #160 

Do you have any opinion on this? Thanks

**Comment by xVanjaZ** [comment] 2022-10-12 21:30
I am running into the same issue, this time with D inversions.
The thing is, the order in which`chord.detect()` is returning "inconsistent".
![image](https://user-images.githubusercontent.com/20064029/195449540-24a47264-8b98-46f7-806c-a90afe8d9dbe.png)
I was expecting `DM/F#` to be index 0, but it is not.

I did find a way to bypass the issue for now, the steps are as follow:
1. Do `chord.detect()`
2. Get `[0]`
3. If the last character is a number, that means we have to take `[1]`

Here is a snippet that seems to work for for me with simple inversions (both 1st and 2nd on majors, minors, augmented and diminished). Haven't tested any edge cases 

```
const chords = Chords.detect(notes);
let result = chords[0];

const char = result[result.length - 1];
if (Number(char)) {
    result = chords[1];
}

console.log(result);
```

**Comment by gotthehot** [comment] 2023-11-17 11:01
Using actual version of [midi-jar](https://github.com/la-jarre-a-son/midi-jar) with tonal v5 and bumping up to same issues with simple triad inversions.

## First Example

E-A-C triad is expected to be displayed as Am/E but recognizing as C6/E without alternatives

![am-inversion](https://github.com/la-jarre-a-son/midi-jar/assets/17710120/378e792e-5c37-450d-828f-bd78b0ed4457)

Yes, it could be C6 with omitted V, but primary display should be basic minor triad.

## Second Example

Soon I found that inversions are not recognized at all (as in Am/E case) or treating as very uncommon chords for primary display. For example when playing simple D major chord inversion from A (**A-D-F#**) midi-jar displays as main choice a very uncommon **Gb6addb6/A** chord and then small display of **DM/A** that is definitely more relevant in most cases.

![d-inversion](https://github.com/la-jarre-a-son/midi-jar/assets/17710120/f629245f-7323-43ba-af3e-2f36e5338572)

It there any hope for issue to be fixed?

**Comment by danigb** [comment] 2023-11-19 19:59
Hi, 

This seems to be a midi-jar, not a tonal issue. Tonal returns `Am/E` and `DM/A` for the examples you mention.

Also, choosing what to show first is a tricky thing. For now, tonal will return inversions always after chords in root position. You may need to change results order after processed by tonal.

Closing this issue.

**Closed by danigb** 2023-11-19 19:59 UTC

**Comment by ArTiSTiX** [comment] 2023-11-19 20:11
@danigb @gotthehot Confirmed it's a bug on my end (midi-jar).
I updated the chord-detect algorithm to handle omissions from an updated dictionary (hope to submit a PR at one time), and i inverted the weight of omissions in inversions.
