### ISSUE TITLE
Scale.detect() is producing incorrect results when using a tonic outside the list of provided notes

### ISSUE THREAD

**Issue by alindsay55661** [tonaljs/tonal#377] opened 2023-04-17 21:05 UTC
```js
Scale.detect(['Ab', 'Gb', 'C', 'Db'], { tonic: 'C#' })) // => 
/*
[
  'C# major',
  'C# melodic minor',
  'C# harmonic minor',
  'C# bebop',
  'C# ionian pentatonic',
  'C# minor #7M pentatonic',
  'C# minor hexatonic',
  "C# messiaen's mode #5",
  'C# augmented heptatonic',
  'C# balinese',
  'C# neopolitan major',
  'C# harmonic major',
  'C# double harmonic major',
  "C# messiaen's mode #4",
  'C# purvi raga',
  'C# bebop major',
  'C# minor bebop',
  'C# ichikosucho',
  'C# minor six diminished',
  'C# kafi raga',
  "C# messiaen's mode #7",
  'C# chromatic'
]
*/
```
C# Major definitely does not include a C natural.

Whereas using `C` as the tonic works fine... or at least I think it does, I haven't double checked the results! :)

```js
Scale.detect(['Ab', 'Gb', 'C', 'Db'], { tonic: 'C' })) // => 
/*
[
  'C locrian',
  'C mystery #1',
  'C double harmonic lydian',
  'C altered',
  'C ultralocrian',
  'C todi raga',
  'C persian',
  'C enigmatic',
  "C messiaen's mode #4",
  'C purvi raga',
  'C bebop locrian',
  "C messiaen's mode #7",
  'C chromatic'
]
*/
```

Why am I using a tonic outside of the provided notes? Because I wanted to detect every scale that a given set of notes could belong to. So I am looping over all possible tonics and aggregating the scales accordingly. That's how I found this (bug?). 

Is this expected behavior or a bug?

**Comment by danigb** [comment] 2023-04-25 17:54
As I see it, the problem here is that, when detecting chords, we don't differentiate between enharmonics. In your first example `C#` appears in the scale in the form of `Db`. I'm closing because it's not a bug (not sure if a feature 😂 ) but feel free to reopen if you have suggestion on how to improve

**Closed by danigb** 2023-04-25 17:54 UTC
